### ISSUE TITLE
cluster value

### ISSUE THREAD

**Issue by alligator19** [exaexa/DiffSOM#1]
Dear Respected colleague. 

I want to appreciate your work. Awesome plots. 
I want to ask that if I am looking for my certain single cluster unit (as catagory in which it is falling, will it be possible to find single cluster unit after clustering. that we input any single data point and want to find in which catagory it is. or similar clusters matching that value?

Please if you can comment and help.

**Comment by exaexa** [comment]
Hello,

that is possible -- the clustering is based off the SOM codes (available in `ds$map$codes`), the mapping of individual codes' neighborhoods to actual numbered clusters is also available (`ds$clust`).

If I got your question correctly, you want to classify any arbitrary cell position to see which cluster it would belong to?

To do that, you can classify a cell (n-dimensional point in space, represented as n-dim vector) manually as such:

```R
cell <- c(........your single cell position here.......)
#get the cell's nearest SOM neighbor
closest.som <- FNN::get.knnx(data=ds$map$codes, query=matrix(cell*ds$importance, nrow=1), k=1)$nn.index[1]
#translate the SOM cluster to metacluster (ie. diffsom cluster)
cell.cluster <- ds$clust[closest.som]
```

You should have the classification of the point in `cell.cluster`.

Note that there's also a way to embed complete new datasets into the embedding view, see EmbedSOM docs for the method.

Anyway, please report if there is a use-case for this; if it seems useful I can probably wrap it in a handy function.

**Comment by exaexa** [comment]
Certainly, just set `cell` in my code to the row with 'b' in your data.

It should also work for the whole matrix, classifying it completely at once:

```R
cells <- (your matrix here)
#get the cells' nearest SOM neighbor
closest.som <- FNN::get.knnx(data=ds$map$codes, query=cells %*% diag(ds$importance), k=1)$nn.index
#translate the SOM cluster to metacluster (ie. diffsom cluster)
cell.clusters <- ds$clust[closest.som]
```

`cell.clusters` will be a vector with a cluster number for both `a` and `b`.

No idea about Python though, the cytometry tooling in Python is not as popular as in R.

**Comment by alligator19** [comment]
HI. Brother. 

Great .. !! Love you. 
One more point. 
Any possibly to integrate by python. ?

**Comment by exaexa** [comment]
Great it works. I'll close this; if more people ask I'll probably add a function like Classify or so to run this thing.

Re python, please see the other issue (#2) -- I don't have time to work on that, but any other python programmer should be able to make a port quickly.
